export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const RESET_LOGIN = "RESET_LOGIN"
export const RESET_ERROR = "RESET_ERROR"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILED = "LOGOUT_FAILED"
export const SET_BASEURL = 'SET_BASEURL'

export const PROFILE_REQUEST = "PROFILE_REQUEST"
export const PROFILE_SUCCESS = "PROFILE_SUCCESS"
export const PROFILE_FAILED = "PROFILE_FAILED"

export const ORDER_REQUEST = "ORDER_REQUEST"
export const ORDER_SUCCESS = "ORDER_SUCCESS"
export const ORDER_FAILED = "ORDER_FAILED"
export const ORDER_RESET = "ORDER_RESET"

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAILED = "ORDER_DETAILS_FAILED"

export const DASHBOARD_REQUEST = "DASHBOARD_REQUEST"
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS"
export const DASHBOARD_FAILED = "DASHBOARD_FAILED"

export const CLIENT_REQUEST = "CLIENT_REQUEST"
export const CLIENT_SUCCESS = "CLIENT_SUCCESS"
export const CLIENT_FAILED = "CLIENT_FAILED"
export const QTY_CHECK = "QTY_CHECK"

export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS"
export const POST_ORDER_FAILED = "POST_ORDER_FAILED"

export const RECEIVABLE_REQUEST = "RECEIVABLE_REQUEST"
export const RECEIVABLE_SUCCESS = "RECEIVABLE_SUCCESS"
export const RECEIVABLE_FAILED = "RECEIVABLE_FAILED"

export const PICKUP_REQUEST = "PICKUP_REQUEST"
export const PICKUP_SUCCESS = "PICKUP_SUCCESS"
export const PICKUP_FAILED = "PICKUP_FAILED"

export const PAYMENTS_REQUEST = "PAYMENTS_REQUEST"
export const PAYMENTS_SUCCESS = "PAYMENTS_SUCCESS"
export const PAYMENTS_FAILED = "PAYMENTS_FAILED"

export const RESERVED_REQUEST = "RESERVED_REQUEST"
export const RESERVED_SUCCESS = "RESERVED_SUCCESS"
export const RESERVED_FAILED = "RESERVED_FAILED"

export const CUSTOMER_REQUEST = "CUSTOMER_REQUEST"
export const CUSTOMER_SUCCESS = "CUSTOMER_SUCCESS"
export const CUSTOMER_FAILED = "CUSTOMER_FAILED"
export const CLIENT_RESET = "CLIENT_RESET"

export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
export const PRODUCT_FAILED = "PRODUCT_FAILED"
export const PRODUCT_RESET = "PRODUCT_RESET"