export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILED = "LOGOUT_FAILED"
export const SET_BASEURL = 'SET_BASEURL'

export const PROFILE_REQUEST = "PROFILE_REQUEST"
export const PROFILE_SUCCESS = "PROFILE_SUCCESS"
export const PROFILE_FAILED = "PROFILE_FAILED"

export const ORDER_REQUEST = "ORDER_REQUEST"
export const ORDER_SUCCESS = "ORDER_SUCCESS"
export const ORDER_FAILED = "ORDER_FAILED"
export const ORDER_RESET = "ORDER_RESET"

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAILED = "ORDER_DETAILS_FAILED"

export const DASHBOARD_REQUEST = "DASHBOARD_REQUEST"
export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS"
export const DASHBOARD_FAILED = "DASHBOARD_FAILED"

export const CLIENT_REQUEST = "CLIENT_REQUEST"
export const CLIENT_SUCCESS = "CLIENT_SUCCESS"
export const CLIENT_FAILED = "CLIENT_FAILED"
export const QTY_CHECK = "QTY_CHECK"

export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS"
export const POST_ORDER_FAILED = "POST_ORDER_FAILED"